### PR TITLE
WW-5446 Fixes deprecated code and missing dependencies

### PR DESCRIPTION
**Pull request by lukaszlenart**
Refs [WW-5446](https://issues.apache.org/jira/browse/WW-5446)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
@burtonrhodes another small step, you can the build [here](https://dist.apache.org/repos/dist/dev/struts/idea-plugin/struts-2024.4.2.zip)

**Comment by burtonrhodes** [comment]
Thanks - still experiencing the same issue though. :-/

**Comment by lukaszlenart** [comment]
But you mean just suggesting JSP pages in `<result>` is missing? I know and trying to figure out what's wrong, addressed all the dependencies and deprecated code hopping this will help :\

**Comment by burtonrhodes** [comment]
After playing around with it, the autocomplete does work now and they are clickable.  I realized I did not have the "web" module added in my Project Structure.  After adding the appropriate module configuration, all of the files in my /webapp/** directory are available in the auto complete list.  After inserting; however, they are still showing up red.  But definitely a workable solution as-is.  Apologies for not noticing the missing Web module configuration earlier.

**Comment by lukaszlenart** [comment]
Hm... it doesn't work for me, I already had the web module defined yet no JSPs in autocomplete, and no red lines :\

**Comment by lukaszlenart** [comment]
Now it works 🤦 - could you share path of your JSPs? I only whitelisted JSPs from /WEB-INF/**

**Comment by burtonrhodes** [comment]
I have my jsps in the following folder structure

```
[module]
/src
    /webapp
        /js
        /struts    <-- jsps are here
        /WEB-INF
        ...etc
```

and in my web.xml I deny access to that folder
```
<security-constraint>
    <web-resource-collection>
        <web-resource-name>Restricted Assets</web-resource-name>
        <url-pattern>/struts/*</url-pattern>
        <url-pattern>/META-INF/*</url-pattern>
    </web-resource-collection>
</security-constraint>
```

That said, is there a security reason why you would whitelist or limit where to look for jsps?  I feel like the entire module (or at least webapp directory) would be fair game for a search/autocomplete inside an IDE.

**Comment by lukaszlenart** [comment]
No real reason, just WEB-INF isn't accessible by default, I will update the pattern

**Comment by burtonrhodes** [comment]
Can you bump the IntelliJ version number from 241 -> 242 in `build.gradle.kts`?  It won't install as I have the latest version of IntelliJ.  Also, is there a way to future proof that `untilBuild.set("242.*")` line?  Omitting it doesn't seem to help, but maybe put something like `untilBuild.set("250.*")`?  It seems unnecessary to have to rebuild/publish the entire plugin for small IDE upgrades which they tend to do many times per year.

Lastly, you might consider doing a search/replace for the string "Struts 2" in the code base.  Probably more appropriate to display "Struts" to the end user instead.

My IntelliJ version
```
IntelliJ IDEA 2024.2.1 (Ultimate Edition)
Build #IU-242.21829.142, built on August 28, 2024
```

**Comment by lukaszlenart** [comment]
This isn't that easy, I also must keep `version.set("2024.2.1")` in sync and they are removing/changing the Platform code with each version, so I must manually introduce changes.

**Comment by lukaszlenart** [comment]
I'm going to merge this as I'm working on better build & release process

**Pull request merged**
